name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master   # Checkout
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Build documentation
      uses: actions/setup-node@v1     # Node.js
      with:
        node-version: 12.x
    - run: npm install                # Install dependencies
    - run: npm run doc                # Build the doc
    - name: Commit        
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add doc/server -f
        git commit -m "generate documentation"
    - name: Push changes              # Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
