name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies and clean
      run: |
        npm install
        npm run clean
    - name: Build the doc
      run: npm run doc
    - name: Commit        
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add doc/server -f
        git commit -m "generate documentation"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
